### PR TITLE
Access table cell label

### PR DESCRIPTION
**Pull request by nikitawani07**
### Platforms Impacted
- [x] iOS
- [ ] macOS

### Description of changes

Since title and subtitle are private, hence made them public.

### Pull request checklist

This PR has considered:
- [x] Light and Dark appearances
- [x] VoiceOver and Keyboard Accessibility
- [x] Internationalization and Right to Left layouts
- [x] Different resolutions (1x, 2x, 3x)
- [x] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/fluentui-apple/pull/285)

### CODE REVIEW

**Comment by harrieshin** [comment]
why do you need access? tableviewcell has been carefully design to make a lot of the info private

**Comment by nikitawani07** [comment]
> why do you need access? tableviewcell has been carefully design to make a lot of the info private

To show tooltip for the labels

**Comment by harrieshin** [comment]
> To show tooltip for the labels

I am not sure this is the right approach. these are static views and not interact-able. why would we show a tooltip?

**Comment by nikitawani07** [comment]
> > To show tooltip for the labels
> 
> I am not sure this is the right approach. these are static views and not interact-able. why would we show a tooltip?

For truncated file names.
I need access to label so that tooltip can be enabled on it. Since it was private, made them public.
Is there any other approach?

**Comment by anandrajeswaran** [comment]
> > > To show tooltip for the labels
> > 
> > 
> > I am not sure this is the right approach. these are static views and not interact-able. why would we show a tooltip?
> 
> For truncated file names.
> I need access to label so that tooltip can be enabled on it. Since it was private, made them public.
> Is there any other approach?

What's the interaction that will show the tooltip? Static text labels are not usually interactable elements so I'm not sure users would really benefit from it, but if we're adding some way to dynamically "expand" a truncated label it probably should be added in the toolkit and FluentUI itself?

**Comment by nikitawani07** [comment]
> > > > To show tooltip for the labels
> > > 
> > > 
> > > I am not sure this is the right approach. these are static views and not interact-able. why would we show a tooltip?
> > 
> > 
> > For truncated file names.
> > I need access to label so that tooltip can be enabled on it. Since it was private, made them public.
> > Is there any other approach?
> 
> What's the interaction that will show the tooltip? Static text labels are not usually interactable elements so I'm not sure users would really benefit from it, but if we're adding some way to dynamically "expand" a truncated label it probably should be added in the toolkit and FluentUI itself?

Enabling the user interaction for the label and adding fluent Tooltip as UILongPressGestureRecognizer action.

**Comment by harrieshin** [comment]
usually Apple cells just show more lines of the label to avoid truncated text. I am not sure users will know they need to long press to see more? also that means the first responder chain gets different by showing the tooltip right?

**Comment by nikitawani07** [comment]
> usually Apple cells just show more lines of the label to avoid truncated text. I am not sure users will know they need to long press to see more? also that means the first responder chain gets different by showing the tooltip right?

Tooltip will be shown for all the truncated texts in the app. So, it would be intuitive for user to long press in the cell as well.

**Comment by anandrajeswaran** [comment]
> > usually Apple cells just show more lines of the label to avoid truncated text. I am not sure users will know they need to long press to see more? also that means the first responder chain gets different by showing the tooltip right?
> 
> Tooltip will be shown for all the truncated texts in the app. So, it would be intuitive for user to long press in the cell as well.

Sorry just catching up so apologies if this has already happened, but we should start a conversation with PM/design pushing for this experience. Apple doesn't show tooltips for truncated text elsewhere on the problem so I'd be surprised if users were able to discover this behavior. Per @harrieshin's comments we should probably be handling this the way Apple does in their first party apps to ensure we meet user expectations

**Pull request closed without merging**
