### PR TITLE
Update version to 0.22.2

### PR DESCRIPTION
**Pull request by alexanderboswell**
##Release notes:
- #1897
- #1900
- #1902
- #1904

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/fluentui-apple/pull/1898)

### CODE REVIEW

**Review by huwilkes — APPROVED** [review]

**Comment by harrieshin** [comment]
the PR description should contain the release notes of this version.

**Comment by alexanderboswell** [comment]
@harrieshin updated the description.

**Review by laminesm — APPROVED** [review]

**Comment by harrieshin** [comment]
make sure all the PR link you are adding in the descriptions are the ones that is for main_0.22 branch not the main on.

**Comment by alexanderboswell** [comment]
> make sure all the PR link you are adding in the descriptions are the ones that is for main_0.22 branch not the main on.

@harrieshin, the goal was to include everything that is pulled in #1902, as it is cherry picking multiple things from main at once. ill update it

**Review by harrieshin — APPROVED** [review]

**Comment by alexanderboswell** [comment]
@harrieshin if you have a chance to take a look and possibly override to commit, seems like the tests are not reliable, in which this PR is just bumping strings so it shouldnt be related.

**Pull request merged**
