### PR TITLE
Adding new items to the PR checklist.

### PR DESCRIPTION
**Pull request by rdeassis**
### Platforms Impacted
- [x] iOS
- [x] macOS

### Description of changes

In light of the evolution of Apple's technology and the addition of new features to the FluentUI library, some new PR validation checklist items are being suggested:

- [x] iOS supported versions (all major versions greater than or equal current target deployment version)
- [x] iPad [Pointer interaction](https://developer.apple.com/documentation/uikit/pointer_interactions)
- [x] [SwiftUI](https://developer.apple.com/tutorials/swiftui) consumption (validation or new demo scenarios needed)
- [x] Objective-C exposure (provide it only if needed)

### Verification

This list is open for discussion and suggestions. Feel free to provide your thoughts on it.

### Pull request checklist

This PR has considered:
- [ ] Light and Dark appearances
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/fluentui-apple/pull/821)

### CODE REVIEW

**Comment by harrieshin** [comment]
without actual public document of the design token info, I am not sure people would know what they need to check.

**Comment by harrieshin** [comment]
same comment for SwiftUI validation. iPad Pointer maybe we can point to apple doc what it is...

**Comment by rdeassis** [comment]
> same comment for SwiftUI validation. iPad Pointer maybe we can point to apple doc what it is...

How about adding linking this URL in the checklist item?
https://developer.apple.com/documentation/uikit/pointer_interactions

**Comment by rdeassis** [comment]
> without actual public document of the design token info, I am not sure people would know what they need to check.

I see your point on not listing design tokens if there's no public documentation on our end. I can remove it.

SwiftUI seems to me as a different case as we're shipping SwiftUI controls on main. Thoughts?

**Comment by harrieshin** [comment]
> > without actual public document of the design token info, I am not sure people would know what they need to check.
> 
> I see your point on not listing design tokens if there's no public documentation on our end. I can remove it.
> 
> SwiftUI seems to me as a different case as we're shipping SwiftUI controls on main. Thoughts?

I think there should some guidance here. make sure UIKit and swiftui apps can use our component. similar to objc and swift clients. but I don't know it is obvious to the community.

**Comment by mischreiber** [comment]
> > > without actual public document of the design token info, I am not sure people would know what they need to check.
> > 
> > 
> > I see your point on not listing design tokens if there's no public documentation on our end. I can remove it.
> > SwiftUI seems to me as a different case as we're shipping SwiftUI controls on main. Thoughts?
> 
> I think there should some guidance here. make sure UIKit and swiftui apps can use our component. similar to objc and swift clients. but I don't know it is obvious to the community.

Interesting point: our test app generally does not exercise any of our components' Objective-C interops. It's a bit of a hole, but it would be quite a bit more work to fully test everything across all three possible consumption models:
- SwiftUI
- UIKit (Swift)
- UIKit (Objective-C)

But maybe I just talked myself into wanting that?

**Comment by rdeassis** [comment]
> > > > without actual public document of the design token info, I am not sure people would know what they need to check.
> > > 
> > > 
> > > I see your point on not listing design tokens if there's no public documentation on our end. I can remove it.
> > > SwiftUI seems to me as a different case as we're shipping SwiftUI controls on main. Thoughts?
> > 
> > 
> > I think there should some guidance here. make sure UIKit and swiftui apps can use our component. similar to objc and swift clients. but I don't know it is obvious to the community.
> 
> Interesting point: our test app generally does not exercise any of our components' Objective-C interops. It's a bit of a hole, but it would be quite a bit more work to fully test everything across all three possible consumption models:
> 
> * SwiftUI
> * UIKit (Swift)
> * UIKit (Objective-C)
> 
> But maybe I just talked myself into wanting that?

I think this is a list of potential applicable tests/validations to a specific change. Not a list of mandatory test gate that all PRs need to go through.

I agree that testing all the items irrespective of the change being made is too much work with no real accomplishment.

I added the Objective-C item as the UIKit one is just the standard.

**Review by mischreiber — APPROVED** [review]

**Comment by sophialee0416** [comment]
I know this is already approved but should we also consider pod lib lint verification in the checklist or is that an unspoken rule?

**Comment by rdeassis** [comment]
> I know this is already approved but should we also consider pod lib lint verification in the checklist or is that an unspoken rule?

I think it'd be worth adding if it was not part of our PR validation checks.
Now that pod lib lint runs when we create PRs, it should cover the scenario.

**Pull request merged**
