### PR TITLE
Move `fluentTheme` from window to view

### PR DESCRIPTION
**Pull request by mischreiber**
### Platforms Impacted
- [x] iOS
- [ ] macOS

### Description of changes

With this change, any arbitrary `UIView` can now host its own `FluentTheme`. Any view's `fluentTheme` property will now look up the nearest parent with a custom theme and use that, instead of relying just on the window.

Side effect: Components should now check whether their view is a descendent of the changing view before redrawing, as the sender is not guaranteed to be a `UIWindow`.

### Verification

Binary size comparison: this saves 19.1 kB. Neat!

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| 31,882,819 bytes | 31,863,203 bytes |

And a demo that theme changing still works as expected:

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| before | after |

### Pull request checklist

This PR has considered:
- [x] Light and Dark appearances
- [x] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] iPad [Pointer interaction](https://developer.apple.com/documentation/uikit/pointer_interactions)
- [x] [SwiftUI](https://developer.apple.com/tutorials/swiftui) consumption (validation or new demo scenarios needed)
- [x] Objective-C exposure (provide it only if needed)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/fluentui-apple/pull/1219)

### CODE REVIEW

**Comment by harrieshin** [comment]
colorproviding protocol on a window still works in the color demo page?

**Review by laminesm — APPROVED** [review]

**Comment by mischreiber** [comment]
> colorproviding protocol on a window still works in the color demo page?

This branch doesn't have brand colors in the color demo page, so nothing to test there yet.

**Comment by harrieshin** [comment]
> > colorproviding protocol on a window still works in the color demo page?
> 
> This branch doesn't have brand colors in the color demo page, so nothing to test there yet.

image

**Comment by mischreiber** [comment]
> > > colorproviding protocol on a window still works in the color demo page?
> > 
> > 
> > This branch doesn't have brand colors in the color demo page, so nothing to test there yet.
> 
> image

Gotcha, thanks! Yep, that page still works as well:

colors

**Pull request merged**
