### PR TITLE
Bumping to 0.27.0

### PR DESCRIPTION
**Pull request by ghuang24**
### Platforms Impacted
- [x] iOS
- [ ] visionOS
- [ ] macOS

### Changes since 0.26.0
* #1989 
* #1990 
* #1992
* #1993

### Binary change

(how is our binary size impacted -- see https://github.com/microsoft/fluentui-apple/wiki/Size-Comparison)

### Verification

(how the change was tested, including both manual and automated tests)

<details>
<summary>Visual Verification</summary>

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |
</details>

### Pull request checklist

This PR has considered:
- [ ] Light and Dark appearances
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] iPad [Pointer interaction](https://developer.apple.com/documentation/uikit/pointer_interactions)
- [ ] [SwiftUI](https://developer.apple.com/tutorials/swiftui) consumption (validation or new demo scenarios needed)
- [ ] Objective-C exposure (provide it only if needed)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/fluentui-apple/pull/1991)

### CODE REVIEW

**Review by joannaquu — COMMENTED** [review]
The demo plist should be bumped as well. See #1988 as an example

**Review by laminesm — COMMENTED** [review]
Did you follow these steps to bump the version https://github.com/microsoft/fluentui-apple/wiki/Fluent-Version-Update?

**Review by laminesm — COMMENTED** [review]
Also please update the PR with which changes are going into this new version. Reference: https://github.com/microsoft/fluentui-apple/pull/1983

**Review by laminesm — APPROVED** [review]
You'll need admin approval for these changes. Fyi @mischreiber @harrieshin @anandrajeswaran

**Comment by ghuang24** [comment]
@mischreiber I'm new to committing to this repo - is there somewhere else I need to add the update notes? The changes are in the PR description

**Comment by laminesm** [comment]
> @mischreiber I'm new to committing to this repo - is there somewhere else I need to add the update notes? The changes are in the PR description

#1992 was merged yesterday so it should be added to the description as part of 0.27.0 release as well

**Comment by mischreiber** [comment]
One more: 
* #1989

**Review by mischreiber — APPROVED** [review]

**Pull request merged**
