### PR TITLE
Version bump to 0.22.0

### PR DESCRIPTION
**Pull request by alexanderboswell**
### Description of changes

ListItem and ListActionItem https://github.com/microsoft/fluentui-apple/pull/1871

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/fluentui-apple/pull/1879)

### CODE REVIEW

**Review by huwilkes — APPROVED** [review]

**Comment by harrieshin** [comment]
message of the release note doesn't seem accurate. some of the changes already went into 0.21

**Comment by alexanderboswell** [comment]
@harrieshin  I only see 4 commits since the version was last bumped to 0.21.0? 7b05348104db410b684797fbe03aa1be66f2c14a

**Comment by alexanderboswell** [comment]
the version was last updated by @huwilkes but that was on the release branch for 0.21.0, not on main. So some of the changes are listed there when updating from 0.21.0 to 0.21.1, but those are only on that branch.

So bumping here on the main branch we would want to include all of the changes since the last version bump on main, 0.21.0 to 0.22.0

**Comment by harrieshin** [comment]
from the client perspective it should be everything delta of the previous release https://github.com/microsoft/fluentui-apple/releases/tag/0.21.0. seems like @huwilkes you haven't updated the release notes with the latest tag of 0.21? so the description of 0.22 is about whats the delta between 0.21.1 and 0.22

**Review by harrieshin — APPROVED** [review]

**Pull request merged**
