### PR TITLE
Fix bugs on Demo App [M1 machines]

### PR DESCRIPTION
**Pull request by kubalani**
### Platforms Impacted
- [X] iOS
- [ ] macOS

### Description of changes

Currently there are build errors on M1 machine for demo app. 
The App fails to compile Demo App target

Screen Shot 2021-04-27 at 12 05 26 PM

Root cause: 
Build arch arm64 was excluded to support AppCenter in prior commit. 
M1 machine needs arm64 (subset of x86_64) binaries to work successfully on all simulators. 
Excluding them is another workaround but it works only on few simulators. 

Fix:
- Updating AppCenter to latest version resolves this problem as new version adds support for arm64 and previous workarounds are no longer required. 
- Undo arm64 exclusion that was added as a workaround to include older version of AppCenter

Majority of changes (441 files) are due to `pod update` and including `AppCenter` in pods directory that's under version control. 

Manually edited files are below:
ios/FluentUI.Demo/FluentUI.Demo.xcodeproj/project.pbxproj
ios/FluentUI.Demo/FluentUI.Demo/AppDelegate.swift

### Verification

Test app compiles and run on M1 machine. 

Screen Shot 2021-04-27 at 12 02 22 PM

Clean pod lib lint

Screen Shot 2021-04-27 at 12 08 19 PM

AppCenter backend testing is still pending. I will update the description once I have access.

### Pull request checklist

This PR has considered:
- [ ] Light and Dark appearances
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/fluentui-apple/pull/545)

### CODE REVIEW

**Comment by Saadnajmi** [comment]
Looks like you committed Pods files too? Hence 441 files changed?

**Comment by harrieshin** [comment]
> Looks like you committed Pods files too? Hence 441 files changed? Was that by accident or do we need them?

based on PR description, it seems like it was needed to get the m1 supported version. can you explicitly write the pod file was updated?

**Review by sophialee0416 — APPROVED** [review]
Build is working on my machine. Seconding above comments, some clarifications on the changes/new files would be great.

**Comment by harrieshin** [comment]
GitHub is lame and I can't easily jump to find specific files. I see pod file.lock changes but did we actually update pod file itself for demo app?

**Review by harrieshin — APPROVED** [review]

**Comment by kubalani** [comment]
@Saadnajmi , @harrieshin 

I haven't updated the pod file itself. I just ran `pod update` and updated the lock file. The changes are necessary as we source control pods directory. I have also updated the description where changes are manually edited.

**Comment by Saadnajmi** [comment]
I know this is merged, but do we want to be source controlling pod files? That seems wrong to me in general... though I guess that's why our test app has less build steps

**Pull request merged**
