### PR TITLE
[main -> vnext_tokens] Update with latest main changes to unblock SegmentedControl work

### PR DESCRIPTION
**Pull request by huwilkes**
### Platforms Impacted
- [x] iOS
- [ ] macOS

### Description of changes

Update vnext_tokens to have the latest changes from main, so that I can continue working on the SegmentedControl in the vnext_tokens branch. I had to make some changes to the CommandBar and SegmentedControl to make the merge happen. Generally, though, includes changes from:
#1001 
#997 
#987 
#995 
#993 
#992 
#989 
#982 
I had to update the CommandBar demo to use the MSFButton. I also had to add tokens to the CommandBarGroupsView to pass it down to the CommandBarButtons, and I had to update the SegmentedControl's icons to use the token colors.
### Verification

Built locally and verified that the changed controls are behaving as expected between main and vnext_tokens.

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| CommandBar_before | CommandBar_after |
| SegmentedControl_before | SegmentedControl_after |

### Pull request checklist

This PR has considered:
- [ ] Light and Dark appearances
- [x] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] iPad [Pointer interaction](https://developer.apple.com/documentation/uikit/pointer_interactions)
- [ ] [SwiftUI](https://developer.apple.com/tutorials/swiftui) consumption (validation or new demo scenarios needed)
- [ ] Objective-C exposure (provide it only if needed)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/fluentui-apple/pull/1003)

### CODE REVIEW

**Comment by harrieshin** [comment]
screenshots?

**Comment by harrieshin** [comment]
"I had to update the CommandBar demo to use the MSFButton. I also had to add tokens to the CommandBarGroupsView to pass it down to the CommandBarButtons, and I had to update the SegmentedControl's icons to use the token colors." which commit is that on your branch?

**Comment by huwilkes** [comment]
> "I had to update the CommandBar demo to use the MSFButton. I also had to add tokens to the CommandBarGroupsView to pass it down to the CommandBarButtons, and I had to update the SegmentedControl's icons to use the token colors." which commit is that on your branch?

Just the last merge one has all of those, since they were more or less needed to fix merge conflicts and build issues.

**Comment by harrieshin** [comment]
for these type of merges, we shouldn't be squash merging right? @mischreiber  / @amgleitman  ? what are the best practices to keep the history clean?

**Comment by harrieshin** [comment]
> > "I had to update the CommandBar demo to use the MSFButton. I also had to add tokens to the CommandBarGroupsView to pass it down to the CommandBarButtons, and I had to update the SegmentedControl's icons to use the token colors." which commit is that on your branch?
> 
> Just the last merge one has all of those, since they were more or less needed to fix merge conflicts and build issues.

when i look at [46853db](https://github.com/microsoft/fluentui-apple/pull/1003/commits/46853db405aa345520f579aed0b08462c5b197ad) i can't see just the command bar changes. am i not looking at it correctly?

**Comment by huwilkes** [comment]
> > > "I had to update the CommandBar demo to use the MSFButton. I also had to add tokens to the CommandBarGroupsView to pass it down to the CommandBarButtons, and I had to update the SegmentedControl's icons to use the token colors." which commit is that on your branch?
> > 
> > 
> > Just the last merge one has all of those, since they were more or less needed to fix merge conflicts and build issues.
> 
> when i look at [46853db](https://github.com/microsoft/fluentui-apple/pull/1003/commits/46853db405aa345520f579aed0b08462c5b197ad) i can't see just the command bar changes. am i not looking at it correctly?

When I look at that, I see all of the changes that were merged in. The changes I made to make the merge work aren't in a different change, but they're in there. With the CommandBar demo, it should be using MSFButtons instead of Buttons, and the SegmentedControl should be getting colors for the icons from the tokens. The CommandBarGroups should have a tokens value, that when set will go and update all of their buttons.

**Comment by harrieshin** [comment]
> > > > "I had to update the CommandBar demo to use the MSFButton. I also had to add tokens to the CommandBarGroupsView to pass it down to the CommandBarButtons, and I had to update the SegmentedControl's icons to use the token colors." which commit is that on your branch?
> > > 
> > > 
> > > Just the last merge one has all of those, since they were more or less needed to fix merge conflicts and build issues.
> > 
> > 
> > when i look at [46853db](https://github.com/microsoft/fluentui-apple/pull/1003/commits/46853db405aa345520f579aed0b08462c5b197ad) i can't see just the command bar changes. am i not looking at it correctly?
> 
> When I look at that, I see all of the changes that were merged in. The changes I made to make the merge work aren't in a different change, but they're in there. With the CommandBar demo, it should be using MSFButtons instead of Buttons, and the SegmentedControl should be getting colors for the icons from the tokens. The CommandBarGroups should have a tokens value, that when set will go and update all of their buttons.

I think we should always have "pure merge" commit as is and have separate commits for fixing per issues. RNmacOS merge follow these practices which helps people understand what they should focus on reviewing https://github.com/microsoft/react-native-macos/pull/1191

**Review by harrieshin — APPROVED** [review]

**Review by mischreiber — APPROVED** [review]

**Review by edjamesmsft — APPROVED** [review]

**Comment by huwilkes** [comment]
> for these type of merges, we shouldn't be squash merging right? @mischreiber / @amgleitman ? what are the best practices to keep the history clean?

Should I "Rebase and merge", then?

**Comment by mischreiber** [comment]
> > for these type of merges, we shouldn't be squash merging right? @mischreiber / @amgleitman ? what are the best practices to keep the history clean?
> 
> Should I "Rebase and merge", then?

Rebasing at this point is probably a lost cause; I can't imagine how many diffs would need to be re-applied to `main` to get `vnext-tokens` caught back up.

That said, I do like @harrieshin's proposal to separate commits for merge vs any fixing to get the build running again.

**Pull request merged**
