### PR TITLE
[Fluent 2 iOS] NotificationView colors update

### PR DESCRIPTION
**Pull request by laminesm**
### Platforms Impacted
- [x] iOS
- [ ] macOS

### Description of changes

NotificationView colors were updated to match fluent 2 tokens. There is also a change updating yellow shade 30 hex value. 

### Verification

the changes were tested on the demo app.

**SwiftUI demo**

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| before_swiftui_primary_toast_light | after_swiftui_primary_toast_light |
| before_swiftui_primary_toast_dark | after_swiftui_primary_toast_dark |
| before_swiftui_neutral_toast_light | after_swiftui_neutral_toast_light |
| before_swiftui_neutral_toast_dark | after_swiftui_neutral_toast_dark |
| before_swiftui_warning_toast_light | after_swiftui_warning_toast_light |
| before_swiftui_warning_toast_dark | after_swiftui_warning_toast_dark |
| before_swiftui_danger_toast_light | after_swiftui_danger_toast_light |
| before_swiftui_danger_toast_dark | after_swiftui_danger_toast_dark |
| before_swiftui_primary_bar_light | after_swiftui_primary_bar_light |
| before_swiftui_primary_bar_dark | after_swiftui_primary_bar_dark |
| before_swiftui_neutral_bar_light | after_swiftui_neutral_bar_light |
| before_swiftui_neutral_bar_dark | after_swiftui_neutral_bar_dark |
| before_swiftui_primary_outline_bar_light | after_swiftui_primary_outline_bar_light |
| before_swiftui_primary_outline_bar_dark | after_swiftui_primary_outline_bar_dark |

**UIKit demo**

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| before_primary_toast_light | after_primary_toast_light |
| before_primary_toast_dark | after_primary_toast_dark |
| before_neutral_toast_light | after_neutral_toast_light |
| before_neutral_toast_dark | after_neutral_toast_dark |
| before_warning_toast_light | after_warning_toast_light |
| before_warning_toast_dark | after_warning_toast_dark |
| before_danger_toast_light | after_danger_toast_light |
| before_danger_toast_dark | after_danger_toast_dark |
| before_primary_bar_light | after_primary_bar_light |
| before_primary_bar_dark | after_primary_bar_dark |
| before_neutral_bar_light | after_neutral_bar_light |
| before_neutral_bar_dark | after_neutral_bar_dark |
| before_primary_outline_bar_light | after_primary_outline_bar_light |
| before_primary_outline_bar_dark | after_primary_outline_bar_dark |

### Pull request checklist

This PR has considered:
- [x] Light and Dark appearances
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] iPad [Pointer interaction](https://developer.apple.com/documentation/uikit/pointer_interactions)
- [x] [SwiftUI](https://developer.apple.com/tutorials/swiftui) consumption (validation or new demo scenarios needed)
- [ ] Objective-C exposure (provide it only if needed)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/fluentui-apple/pull/1202)

### CODE REVIEW

**Comment by harrieshin** [comment]
for the subtle messagebar case are we suppose to have divider top and bottom? the screenshot seems like there is 2.

**Comment by harrieshin** [comment]
would you please check the text to background color contrast ratio of neutral bar is good?

**Comment by harrieshin** [comment]
these changes are significant enough we should call it out on our fluent 2 update annoucements

**Review by sophialee0416 — APPROVED** [review]
Looks good as long as the color contrast check passes!

**Comment by laminesm** [comment]
> would you please check the text to background color contrast ratio of neutral bar is good?

All contrast ratios were checked and have passed. The only issue found was with warning style because the hex value of shade 30 was incorrect.

**Pull request merged**
