### PR TITLE
Add Obj-C support to tableCellBackgroundSelected color

### PR DESCRIPTION
**Pull request by cy255**
### Platforms Impacted
- [x] iOS
- [ ] macOS

### Description of changes
Add Obj-C support to table cell's selected background color.

### Verification
-Verified that the added tableCellBackgroundSelected public Obj-C variable is available in the generated FluentUI-Swift.h file.

### Pull request checklist

This PR has considered:
- [x] Light and Dark appearances
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/fluentui-apple/pull/550)

### CODE REVIEW

**Comment by harrieshin** [comment]
curious why you are changing the selection color?

**Review by harrieshin — APPROVED** [review]

**Review by Saadnajmi — APPROVED** [review]

**Comment by cy255** [comment]
> curious why you are changing the selection color?

@harrieshin custom TableViewCells (non Fluent tableViewCells) might want to adopt a similar Fluent appearance

**Comment by harrieshin** [comment]
> > curious why you are changing the selection color?
> 
> @harrieshin custom TableViewCells (non Fluent tableViewCells) might want to adopt a similar Fluent appearance

that's weird. you are using fluent tableviewcell but don't want to look like fluent selection?

**Review by rdeassis — APPROVED** [review]

**Comment by cy255** [comment]
> > > curious why you are changing the selection color?
> > 
> > 
> > @harrieshin custom TableViewCells (non Fluent tableViewCells) might want to adopt a similar Fluent appearance
> 
> that's weird. you are using fluent tableviewcell but don't want to look like fluent selection?

I should have reworded it better. A non Fluent tableViewCell wants to look like Fluent tableViewCell on selection.

**Pull request merged**
