### PR TITLE
turn on address sanitizer for fluent development scheme

### PR DESCRIPTION
**Pull request by harrieshin**
…uent ios and macOS demo app.

### Platforms Impacted
- [x] iOS
- [x] macOS

### Description of changes
Turn on ASan and UBSan for development scheme in macOS and iOS

### Verification
Build and run the demo app

### Pull request checklist

This PR has considered:
- [ ] Light and Dark appearances
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] iPad [Pointer interaction](https://developer.apple.com/documentation/uikit/pointer_interactions)
- [ ] [SwiftUI](https://developer.apple.com/tutorials/swiftui) consumption (validation or new demo scenarios needed)
- [ ] Objective-C exposure (provide it only if needed)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/fluentui-apple/pull/837)

### CODE REVIEW

**Comment by mischreiber** [comment]
Looks like UTs are failing?

**Comment by harrieshin** [comment]
> Looks like UTs are failing?

thanks for your patience. i finally got it working.

**Comment by rdeassis** [comment]
> > Looks like UTs are failing?
> 
> thanks for your patience. i finally got it working.

Curious on what was the issue and the cause of the failed tests.

**Review by rdeassis — APPROVED** [review]

**Comment by harrieshin** [comment]
> > > Looks like UTs are failing?
> > 
> > 
> > thanks for your patience. i finally got it working.
> 
> Curious on what was the issue and the cause of the failed tests.

all the test related frameworks needed to have the asan/ubsan turned on and the xctestplan configuration should follow the default configuration.

**Pull request merged**
