### PR TITLE
Allow HUD to grow for long texts

### PR DESCRIPTION
**Pull request by joannaquu**
### Platforms Impacted
- [x] iOS
- [ ] macOS

### Description of changes

Fixed a bug with `HUD` where HUDs with long labels would truncate before growing to the `maxSize`. This was because size started at `minSize`, limiting `viewDimensions`, which was used to calculate `size`. This change starts size at `maxSize` instead.

### Binary change

Total increase: 0 bytes
Total decrease: -512 bytes
| File | Before | After | Delta |
|------|-------:|------:|------:|
| Total | 44,604,888 bytes | 44,604,376 bytes | 🎉 -512 bytes |
<details>
<summary> Full breakdown </summary>

| File | Before | After | Delta |
|------|-------:|------:|------:|
| HUDModifiers.o | 125,296 bytes | 124,784 bytes | 🎉 -512 bytes |
</details>

### Verification

<details>
<summary>Visual Verification</summary>

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 17 50 45 | Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 17 56 18 |
| Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 15 55 29 | Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 17 57 53 |
| Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 15 55 33 | Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 17 57 57 |
| Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 15 55 35 | Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 17 58 02 |
| Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 15 55 36 | Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 17 58 06 |
| Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 15 55 38 | Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 17 58 11 |
| Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 15 55 43 | Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 17 58 32 |
| Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 15 55 47 | Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 17 58 36 |
| Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 15 55 54 | Simulator Screen Shot - iPhone 14 Pro - 2023-03-23 at 17 58 50 |
</details>

### Pull request checklist

This PR has considered:
- [ ] Light and Dark appearances
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] iPad [Pointer interaction](https://developer.apple.com/documentation/uikit/pointer_interactions)
- [ ] [SwiftUI](https://developer.apple.com/tutorials/swiftui) consumption (validation or new demo scenarios needed)
- [ ] Objective-C exposure (provide it only if needed)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/fluentui-apple/pull/1667)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/fluentui-apple/pull/1667)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/fluentui-apple/pull/1667)

### CODE REVIEW

**Comment by harrieshin** [comment]
let's also check the large accessibility text size?

**Comment by joannaquu** [comment]
> let's also check the large accessibility text size?

With a larger text size, it'll truncate once it hits `maxSize` (192)

Screen Shot 2022-06-14 at 11 24 37 AM

**Comment by harrieshin** [comment]
i don't think the starting with max size is correct ? then there is no point of having min size, i think the minsize calculation might be wrong when there is longer text?

**Comment by joannaquu** [comment]
> i don't think the starting with max size is correct ? then there is no point of having min size, i think the minsize calculation might be wrong when there is longer text?

So I did some testing with the No Label HUD and can confirm `minSize` is being used (the HUD only needs a height of 76 but it updates to be 100). What do you think might be wrong with the minSize calculation?

**Comment by harrieshin** [comment]
> > i don't think the starting with max size is correct ? then there is no point of having min size, i think the minsize calculation might be wrong when there is longer text?
> 
> So I did some testing with the No Label HUD and can confirm `minSize` is being used (the HUD only needs a height of 76 but it updates to be 100). What do you think might be wrong with the minSize calculation?

i didn't understand why line 76 change is necessary?

**Comment by joannaquu** [comment]
> > > i don't think the starting with max size is correct ? then there is no point of having min size, i think the minsize calculation might be wrong when there is longer text?
> > 
> > 
> > So I did some testing with the No Label HUD and can confirm `minSize` is being used (the HUD only needs a height of 76 but it updates to be 100). What do you think might be wrong with the minSize calculation?
> 
> i didn't understand why line 76 change is necessary?

Clarified offline: initializing size to `minSize` will limit the label size, limiting `viewDimensions` (the size of the HUD will be calculated to require less space than it actually needs to fit the whole label). Starting at `maxSize` gives long labels all the available space. It can then shrink as needed.

**Review by harrieshin — APPROVED** [review]

**Pull request merged**
