### PR TITLE
Improve SwiftUI theme support

### PR DESCRIPTION
**Pull request by huwilkes**
### Platforms Impacted
- [x] iOS
- [ ] macOS

### Description of changes

Theming has never worked very well in our SwiftUI demos, and there were a few reasons for this:
 - We never passed the theme into the SwiftUI environment from the hosting UIKit demos.
 - While the `.fluentTheme` modifier on `View` was public, allowing users to set the environment variable for the `FluentTheme`, the key to retrieve it was internal. So while our controls could retrieve the theme from the environment, clients could not.
 - Our controls would draw with the correct theme when they initially load, but would change to just the default `.shared` theme on any theme changes. This is due to building up the control with the default theme, and trying to trigger an update by setting the theme in the `tokenSet`. Despite the `fluentTheme` being `@Published`, it wasn't triggering a redraw in SwiftUI, resulting in controls showing the default colors.

The first two points were easy enough to fix: 
 - Add a `fluentTheme` var to the SwiftUI demo views, and pass in the theme from the `UIHostingController`.
 - Make it public.

The last point was more involved, though. Since the actual control had the right theme the whole time, the issue was just the `tokenSet` not having it. While the `tokenSet`'s `fluentTheme` was `@Published`, trying to set it while drawing would result in this warning:
`[SwiftUI] Publishing changes from within view updates is not allowed, this will cause undefined behavior.`
Which we clearly don't want.
So to get the behavior we did want in SwiftUI without warnings, I removed `@Published` - which caused theming to break in UIKit. After #1628, the UIKit controls were listening for their `tokenSet` to tell them that the theme had changed. To fix that break I added a call to the `tokenSet`'s `onUpdate` in the `didSet` of the `fluentTheme`. Since `onUpdate` is optional, and only set during `registerOnUpdate`, this means that only controls that call `registerOnUpdate` will be updated when the `tokenSet`'s theme changes.

While I was working to improve theming support, I figured it was also a good chance to improve theme consistency throughout our demo app. So now when the theme is set to green, everything that was blue before should be green now.

### Binary change

Total increase: 326,904 bytes
Total decrease: -128,608 bytes
| File | Before | After | Delta |
|------|-------:|------:|------:|
| Total | 30,784,512 bytes | 30,982,808 bytes | 🛑 198,296 bytes |
<details>
<summary> Full breakdown </summary>

| File | Before | After | Delta |
|------|-------:|------:|------:|
| TableViewCell.o | 802,288 bytes | 835,720 bytes | ⚠️ 33,432 bytes |
| TabBarItemView.o | 210,320 bytes | 231,424 bytes | ⚠️ 21,104 bytes |
| Button.o | 181,688 bytes | 202,600 bytes | ⚠️ 20,912 bytes |
| TooltipView.o | 201,336 bytes | 222,112 bytes | ⚠️ 20,776 bytes |
| SearchBar.o | 418,760 bytes | 436,768 bytes | ⚠️ 18,008 bytes |
| FluentTextField.o | 190,776 bytes | 206,800 bytes | ⚠️ 16,024 bytes |
| PillButton.o | 160,128 bytes | 175,864 bytes | ⚠️ 15,736 bytes |
| ShimmerView.o | 167,944 bytes | 182,416 bytes | ⚠️ 14,472 bytes |
| SegmentPillButton.o | 85,064 bytes | 97,128 bytes | ⚠️ 12,064 bytes |
| Avatar.o | 582,616 bytes | 593,592 bytes | ⚠️ 10,976 bytes |
| ActionsCell.o | 158,328 bytes | 168,872 bytes | ⚠️ 10,544 bytes |
| TableViewHeaderFooterView.o | 279,848 bytes | 290,352 bytes | ⚠️ 10,504 bytes |
| SegmentedControl.o | 335,056 bytes | 345,008 bytes | ⚠️ 9,952 bytes |
| CenteredLabelCell.o | 85,336 bytes | 95,152 bytes | ⚠️ 9,816 bytes |
| DrawerController.o | 497,104 bytes | 506,408 bytes | ⚠️ 9,304 bytes |
| BottomSheetController.o | 503,088 bytes | 512,200 bytes | ⚠️ 9,112 bytes |
| __.SYMDEF | 4,642,184 bytes | 4,651,104 bytes | ⚠️ 8,920 bytes |
| ResizingHandleView.o | 72,272 bytes | 81,184 bytes | ⚠️ 8,912 bytes |
| CommandBarButton.o | 97,152 bytes | 105,896 bytes | ⚠️ 8,744 bytes |
| DateTimePickerViewComponentCell.o | 53,632 bytes | 59,592 bytes | ⚠️ 5,960 bytes |
| CommandBar.o | 230,848 bytes | 235,992 bytes | ⚠️ 5,144 bytes |
| TabBarView.o | 130,848 bytes | 135,928 bytes | ⚠️ 5,080 bytes |
| SideTabBar.o | 198,576 bytes | 203,656 bytes | ⚠️ 5,080 bytes |
| Separator.o | 74,200 bytes | 78,536 bytes | ⚠️ 4,336 bytes |
| ActivityIndicatorCell.o | 80,400 bytes | 84,624 bytes | ⚠️ 4,224 bytes |
| MSFNotification.o | 143,536 bytes | 147,200 bytes | ⚠️ 3,664 bytes |
| DrawerShadowView.o | 76,800 bytes | 80,256 bytes | ⚠️ 3,456 bytes |
| DrawerPresentationController.o | 250,728 bytes | 253,800 bytes | ⚠️ 3,072 bytes |
| BooleanCell.o | 93,336 bytes | 96,312 bytes | ⚠️ 2,976 bytes |
| Tooltip.o | 133,824 bytes | 136,792 bytes | ⚠️ 2,968 bytes |
| CommandBarButtonGroupView.o | 59,016 bytes | 61,928 bytes | ⚠️ 2,912 bytes |
| FluentTheme.o | 121,456 bytes | 124,016 bytes | ⚠️ 2,560 bytes |
| CardNudge.o | 437,792 bytes | 439,808 bytes | ⚠️ 2,016 bytes |
| Label.o | 123,784 bytes | 125,216 bytes | ⚠️ 1,432 bytes |
| ShyHeaderView.o | 123,768 bytes | 124,856 bytes | ⚠️ 1,088 bytes |
| BadgeLabel.o | 56,120 bytes | 57,056 bytes | ⚠️ 936 bytes |
| AvatarGroup.o | 362,144 bytes | 362,832 bytes | ⚠️ 688 bytes |
| NavigationBar.o | 545,096 bytes | 545,056 bytes | 🎉 -40 bytes |
| FocusRingView.o | 758,976 bytes | 758,640 bytes | 🎉 -336 bytes |
| PopupMenuTokenSet.o | 20,528 bytes | 20,000 bytes | 🎉 -528 bytes |
| TabBarItemTokenSet.o | 63,584 bytes | 63,048 bytes | 🎉 -536 bytes |
| TableViewHeaderFooterViewTokenSet.o | 83,456 bytes | 82,904 bytes | 🎉 -552 bytes |
| ButtonTokenSet.o | 128,376 bytes | 127,816 bytes | 🎉 -560 bytes |
| BadgeViewTokenSet.o | 99,080 bytes | 98,520 bytes | 🎉 -560 bytes |
| PersonaButtonCarouselTokenSet.o | 43,656 bytes | 43,096 bytes | 🎉 -560 bytes |
| LabelTokenSet.o | 61,384 bytes | 60,816 bytes | 🎉 -568 bytes |
| BottomSheetTokenSet.o | 49,040 bytes | 48,472 bytes | 🎉 -568 bytes |
| ResizingHandleTokenSet.o | 46,464 bytes | 45,896 bytes | 🎉 -568 bytes |
| SideTabBarTokenSet.o | 52,040 bytes | 51,472 bytes | 🎉 -568 bytes |
| HeadsUpDisplayTokenSet.o | 56,264 bytes | 55,688 bytes | 🎉 -576 bytes |
| AvatarTokenSet.o | 123,560 bytes | 122,984 bytes | 🎉 -576 bytes |
| SeparatorTokenSet.o | 42,104 bytes | 41,528 bytes | 🎉 -576 bytes |
| TabBarTokenSet.o | 46,784 bytes | 46,200 bytes | 🎉 -584 bytes |
| AvatarGroupTokenSet.o | 48,728 bytes | 48,144 bytes | 🎉 -584 bytes |
| IndeterminateProgressBarTokenSet.o | 45,592 bytes | 45,008 bytes | 🎉 -584 bytes |
| DrawerTokenSet.o | 56,984 bytes | 56,400 bytes | 🎉 -584 bytes |
| CommandBarTokenSet.o | 66,952 bytes | 66,368 bytes | 🎉 -584 bytes |
| TooltipTokenSet.o | 59,440 bytes | 58,848 bytes | 🎉 -592 bytes |
| EmptyTokenSet.o | 38,968 bytes | 38,368 bytes | 🎉 -600 bytes |
| BottomCommandingController.o | 725,296 bytes | 723,920 bytes | 🎉 -1,376 bytes |
| NotificationTokenSet.o | 94,272 bytes | 92,888 bytes | 🎉 -1,384 bytes |
| SegmentedControlTokenSet.o | 96,704 bytes | 95,312 bytes | 🎉 -1,392 bytes |
| CardNudgeTokenSet.o | 87,224 bytes | 85,832 bytes | 🎉 -1,392 bytes |
| TextFieldTokenSet.o | 96,592 bytes | 95,192 bytes | 🎉 -1,400 bytes |
| TableViewCellTokenSet.o | 114,456 bytes | 113,056 bytes | 🎉 -1,400 bytes |
| PillButtonTokenSet.o | 93,112 bytes | 91,712 bytes | 🎉 -1,400 bytes |
| ShimmerTokenSet.o | 75,824 bytes | 74,416 bytes | 🎉 -1,408 bytes |
| PersonaButtonTokenSet.o | 68,896 bytes | 67,480 bytes | 🎉 -1,416 bytes |
| SearchBarTokenSet.o | 86,056 bytes | 84,640 bytes | 🎉 -1,416 bytes |
| ActivityIndicatorTokenSet.o | 66,120 bytes | 64,672 bytes | 🎉 -1,448 bytes |
| PersonaButton.o | 270,160 bytes | 268,656 bytes | 🎉 -1,504 bytes |
| CalendarViewDayCell.o | 145,008 bytes | 143,240 bytes | 🎉 -1,768 bytes |
| ShimmerLinesView.o | 149,272 bytes | 147,184 bytes | 🎉 -2,088 bytes |
| CardView.o | 275,896 bytes | 273,184 bytes | 🎉 -2,712 bytes |
| PersonaButtonCarousel.o | 196,504 bytes | 193,240 bytes | 🎉 -3,264 bytes |
| IndeterminateProgressBar.o | 279,824 bytes | 275,832 bytes | 🎉 -3,992 bytes |
| ControlTokenSet.o | 83,368 bytes | 78,200 bytes | 🎉 -5,168 bytes |
| ActivityIndicator.o | 196,488 bytes | 191,096 bytes | 🎉 -5,392 bytes |
| FluentNotification.o | 784,048 bytes | 777,904 bytes | 🎉 -6,144 bytes |
| PopupMenuItemCell.o | 184,376 bytes | 177,608 bytes | 🎉 -6,768 bytes |
| PopupMenuItem.o | 140,280 bytes | 133,344 bytes | 🎉 -6,936 bytes |
| HeadsUpDisplay.o | 285,096 bytes | 277,664 bytes | 🎉 -7,432 bytes |
| PopupMenuItemTokenSet.o | 39,240 bytes | 30,864 bytes | 🎉 -8,376 bytes |
| BadgeView.o | 594,296 bytes | 554,448 bytes | 🎉 -39,848 bytes |
</details>

### Verification

Checked every control and demo that was changed in the test app, but will only upload a subset for visual verification here.
I also updated the Notification demo to let me test changing themes in SwiftUI, but that was the only demo I updated to do so.
ThemeSupport_SwiftUI_FullDemo

<details>
<summary>Visual Verification</summary>

| Scenario | Before | After |
|---|---|---|
| UIKit control in UIKit | ThemeSupport_UIKit_Before | ThemeSupport_UIKit_After |
| SwiftUI control in UIKit | ThemeSupport_SwiftUIHosted_Before | ThemeSupport_SwiftUIHosted_After |
| SwiftUI control in SwiftUI | ThemeSupport_SwiftUI_Before | ThemeSupport_SwiftUI_After |
</details>

### Pull request checklist

This PR has considered:
- [x] Light and Dark appearances
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] iPad [Pointer interaction](https://developer.apple.com/documentation/uikit/pointer_interactions)
- [x] [SwiftUI](https://developer.apple.com/tutorials/swiftui) consumption (validation or new demo scenarios needed)
- [ ] Objective-C exposure (provide it only if needed)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/fluentui-apple/pull/1737)

### CODE REVIEW

**Review by laminesm — APPROVED** [review]

**Comment by mischreiber** [comment]
> ⛔️ 384,968 bytes

That's a pretty big increase... is there anything we could do to minimize this impact somehow? Otherwise I don't know if we can justify the hit.

**Comment by huwilkes** [comment]
> > ⛔️ 384,968 bytes
> 
> That's a pretty big increase... is there anything we could do to minimize this impact somehow? Otherwise I don't know if we can justify the hit.

We might be able to lose some of it by removing the new protocol and just adding the observer to all of the UIKit controls directly, but at least part of that increase is from reverting some of the decrease from moving to `registerOnUpdate`.

**Comment by huwilkes** [comment]
> > > ⛔️ 384,968 bytes
> > 
> > 
> > That's a pretty big increase... is there anything we could do to minimize this impact somehow? Otherwise I don't know if we can justify the hit.
> 
> We might be able to lose some of it by removing the new protocol and just adding the observer to all of the UIKit controls directly, but at least part of that increase is from reverting some of the decrease from moving to `registerOnUpdate`.

Never mind, that didn't lead to decreasing the binary size.

**Comment by huwilkes** [comment]
> > > > ⛔️ 384,968 bytes
> > > 
> > > 
> > > That's a pretty big increase... is there anything we could do to minimize this impact somehow? Otherwise I don't know if we can justify the hit.
> > 
> > 
> > We might be able to lose some of it by removing the new protocol and just adding the observer to all of the UIKit controls directly, but at least part of that increase is from reverting some of the decrease from moving to `registerOnUpdate`.
> 
> Never mind, that didn't lead to decreasing the binary size.

Turns out I really only needed to change the `tokenSet`'s `fluentTheme` from `@Published` to calling `onUpdate` in the theme's `didSet`, so I can undo all the changes to move the observer to a protocol and cut the growth significantly.

**Pull request merged**
