### PR TITLE
Add ability to customize TableViewCell separator color

### PR DESCRIPTION
**Pull request by joannaquu**
### Platforms Impacted
- [x] iOS
- [ ] macOS

### Description of changes

Added ability to customize `TableViewCell`'s separator color. A new token `separatorColor` was added to `TableViewCellTokenSet`.

### Binary change

Total increase: 7,704 bytes
Total decrease: 0 bytes
| File | Before | After | Delta |
|------|-------:|------:|------:|
| Total | 30,796,008 bytes | 30,803,712 bytes | ⚠️ 7,704 bytes |
<details>
<summary> Full breakdown </summary>

| File | Before | After | Delta |
|------|-------:|------:|------:|
| TableViewCell.o | 805,384 bytes | 809,800 bytes | ⚠️ 4,416 bytes |
| TableViewCellTokenSet.o | 108,280 bytes | 109,984 bytes | ⚠️ 1,704 bytes |
| __.SYMDEF | 4,770,960 bytes | 4,772,144 bytes | ⚠️ 1,184 bytes |
| PopupMenuItemCell.o | 174,072 bytes | 174,208 bytes | ⚠️ 136 bytes |
| PersonaCell.o | 62,704 bytes | 62,832 bytes | ⚠️ 128 bytes |
| BooleanCell.o | 89,904 bytes | 90,032 bytes | ⚠️ 128 bytes |
| ListActionItem.o | 224,808 bytes | 224,816 bytes | ⚠️ 8 bytes |
</details>

### Verification

<details>
<summary>Visual Verification</summary>

| Light                                       | Dark                                      |
|----------------------------------------------|--------------------------------------------|
| image | image |
</details>

### Pull request checklist

This PR has considered:
- [x] Light and Dark appearances
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] iPad [Pointer interaction](https://developer.apple.com/documentation/uikit/pointer_interactions)
- [ ] [SwiftUI](https://developer.apple.com/tutorials/swiftui) consumption (validation or new demo scenarios needed)
- [ ] Objective-C exposure (provide it only if needed)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/fluentui-apple/pull/1923)

### CODE REVIEW

**Review by harrieshin — APPROVED** [review]

**Review by huwilkes — APPROVED** [review]

**Comment by alexanderboswell** [comment]
Is there a reason this isnt a token on separator control instead of tableViewCell?

**Review by laminesm — APPROVED** [review]
I'd suggest choosing a more drastic override color in the demo like pink so we can see the overridden separator easier since it's a very tiny control.

**Comment by alexanderboswell** [comment]
also, if we want to update in TableViewCell, we should also update here: https://github.com/microsoft/fluentui-apple/blob/main/ios/FluentUI/List/ListActionItem.swift

That was my thought behind doing it in separator instead, then both implementations are going to get the right color without having to set it in each implementation.

**Comment by harrieshin** [comment]
> I'd suggest choosing a more drastic override color in the demo like pink so we can see the overridden separator easier since it's a very tiny control.

not pink. otherwise accessibility vendors will flag our app as not color contrast accessible.

**Comment by joannaquu** [comment]
> we should also update here: https://github.com/microsoft/fluentui-apple/blob/main/ios/FluentUI/List/ListActionItem.swift

Will do in future pr

**Pull request merged**
