### PR TITLE
[fluent2-tokens] Merging main -> fluent2-tokens

### PR DESCRIPTION
**Pull request by sophialee0416**
### Platforms Impacted
- [x] iOS
- [x] macOS

### Description of changes

| File | Before | After | Delta |
|------|--------|-------|-------|
| libFluentUI.a | 32,414,160 bytes | 32,405,448 bytes | -8712 bytes |

### Pull request checklist

This PR has considered:
- [ ] Light and Dark appearances
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] iPad [Pointer interaction](https://developer.apple.com/documentation/uikit/pointer_interactions)
- [ ] [SwiftUI](https://developer.apple.com/tutorials/swiftui) consumption (validation or new demo scenarios needed)
- [ ] Objective-C exposure (provide it only if needed)

### CODE REVIEW

**Review by joannaquu — APPROVED** [review]

**Review by laminesm — COMMENTED** [review]
Curious what is causing this binary change?

**Review by laminesm — APPROVED** [review]

**Comment by edjamesmsft** [comment]
This is a HUGE binary change. I'd be leery of merging this until we understand what's going on

**Review by edjamesmsft — CHANGES_REQUESTED** [review]
Please root-cause the very large binary change before we merge this.

**Comment by sophialee0416** [comment]
> Please root-cause the very large binary change before we merge this.

I don't know where those numbers came from because I just re-ran the builds and the numbers ended up way smaller. 872 byte increase now.

**Review by edjamesmsft — APPROVED** [review]

**Review by mischreiber — APPROVED** [review]

**Pull request merged**
